// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var client, currentMonth, currentYear, defaultTaskList, emptyButton, generateTaskPaperMonth, getLocationParameters, items, itemsField, locationParameters, log, month, nextYear, spliceText, thisYear, today, year;
    log = console.log.bind(console);
    spliceText = function(string, index, charactersToReplace, stringToAdd) {
      return string.slice(0, index) + stringToAdd + string.slice(index + charactersToReplace);
    };
    getLocationParameters = function() {
      var pair, pairs, params, processPair, search, _i, _len;
      params = {};
      search = window.location.search;
      if (!(search != null ? search.length : void 0)) {
        return params;
      }
      pairs = search.slice(1).split('&');
      processPair = function(pair) {
        var key, value, _ref;
        _ref = pair != null ? pair.split('=') : void 0, key = _ref[0], value = _ref[1];
        if (!value) {
          return;
        }
        params[key] = (function() {
          switch (false) {
            case value !== "true":
              return true;
            case value !== "false":
              return false;
            case !!isNaN(Number(value)):
              return Number(value);
            default:
              return decodeURIComponent(value).replace(/\+/g, ' ');
          }
        })();
      };
      for (_i = 0, _len = pairs.length; _i < _len; _i++) {
        pair = pairs[_i];
        processPair(pair);
      }
      return params;
    };
    defaultTaskList = '1\nto-do item\n\n14\nanother task\n\tnotes\n\n29\ntask\nyet another task\n\tnotes and details\n\tanother note';
    if (localStorage.getItem('items')) {
      items = localStorage.getItem('items');
      year = localStorage.getItem('year');
      month = localStorage.getItem('month');
    } else {
      today = new Date();
      items = defaultTaskList;
      year = today.getFullYear();
      month = today.getMonth();
    }
    locationParameters = getLocationParameters();
    if (locationParameters['year'] != null) {
      year = locationParameters['year'];
    }
    if (locationParameters['month'] != null) {
      month = locationParameters['month'];
    }
    itemsField = $('#items');
    thisYear = new Date().getFullYear();
    nextYear = thisYear + 1;
    $('#year-this').attr('id', 'year-' + thisYear).attr('value', thisYear).after($('<label for="year-' + thisYear + '">' + thisYear + '</label>'));
    $('#year-next').attr('id', 'year-' + nextYear).attr('value', nextYear).after($('<label for="year-' + nextYear + '">' + nextYear + '</label>'));
    $('#year-' + year).attr('checked', true);
    $('#month-' + month).attr('checked', true);
    currentMonth = new Date().getMonth() + 1;
    currentYear = new Date().getFullYear();
    $('#month-' + currentMonth).addClass('current-month');
    $('#year-' + currentYear).addClass('current-year');
    itemsField.val(items);
    itemsField.focus();
    (generateTaskPaperMonth = function() {
      var cleanURL, day, dayName, dayNames, dayNumber, generatedMonth, itemsArray, itemsText, nextMonth, numberOfDays, selectedMonth, selectedYear, _i;
      selectedYear = $('input[name="year"]:checked');
      selectedMonth = $('input[name="month"]:checked');
      year = selectedYear.val();
      month = selectedMonth.val() - 1;
      numberOfDays = new Date(year, month, 0).getDate() + 1;
      generatedMonth = '';
      itemsText = $('#items').val();
      itemsArray = itemsText.split(/(\d+):?\n/m);
      itemsArray.shift();
      items = {};
      $.each(itemsArray, function(key, value) {
        if (key % 2 === 0) {
          return items[itemsArray[key]] = itemsArray[key + 1];
        }
      });
      $.each(items, function(key, value) {
        return items[key] = items[key].trim().split('\n');
      });
      for (day = _i = 1; 1 <= numberOfDays ? _i <= numberOfDays : _i >= numberOfDays; day = 1 <= numberOfDays ? ++_i : --_i) {
        dayNames = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
        dayName = dayNames[new Date(year, month, day).getDay()];
        dayNumber = day;
        if (dayNumber > 1) {
          generatedMonth += '\n';
        }
        if (dayNumber < 10) {
          generatedMonth += '0';
        }
        generatedMonth += dayNumber + ' ' + dayName + ':';
        if (items[dayNumber]) {
          $.each(items[dayNumber], function(key, value) {
            if (value.substring(0, 2) === '  ' || value.substring(0, 1) === '\t') {
              return generatedMonth += '\n\t' + value;
            } else if (value.substring(0, 2) === '- ') {
              return generatedMonth += '\n\t' + value;
            } else {
              return generatedMonth += '\n\t- ' + value;
            }
          });
        }
        nextMonth = {};
        if (month === 11) {
          nextMonth['month'] = 1;
          nextMonth['year'] = Number(year) + 1;
        } else {
          nextMonth['month'] = Number(month) + 2;
          nextMonth['year'] = year;
        }
        if (dayNumber === numberOfDays) {
          generatedMonth += '\n\t- generate new Taskpaper month\n\t\thttp://matthewmcvickar.github.io/taskpaper-month-generator?year=' + nextMonth['year'] + '&month=' + nextMonth['month'];
        }
      }
      $('#taskpaper-month').val(generatedMonth);
      cleanURL = window.location.href.substring(0, window.location.href.indexOf('?')) + '?year=' + year + '&month=' + (Number(month) + 1);
      history.pushState({}, '', cleanURL);
      localStorage.setItem('year', selectedYear.val());
      localStorage.setItem('month', selectedMonth.val());
      return localStorage.setItem('items', itemsField.val());
    })();
    itemsField.keydown(function(key) {
      var cursorPosition, itemsFieldValue;
      cursorPosition = itemsField.get(0).selectionStart;
      itemsFieldValue = itemsField.val();
      if (key.keyCode === 9) {
        key.preventDefault();
        itemsField.val(spliceText(itemsFieldValue, cursorPosition, 0, '\t'));
        itemsField.get(0).setSelectionRange(cursorPosition + 1, cursorPosition + 1);
        return false;
      }
    });
    $('input[name="month"]').on('change', generateTaskPaperMonth);
    $('input[name="year"]').on('change', generateTaskPaperMonth);
    itemsField.on('keyup', generateTaskPaperMonth);
    itemsField.on('keyup', function() {
      if (itemsField.val().trim() !== '') {
        return emptyButton.fadeIn('fast');
      } else {
        return emptyButton.fadeOut('fast');
      }
    });
    $('#load-example-tasks-button').click(function() {
      if (itemsField.val().trim() !== '') {
        $('#confirm-recall-of-defaults').fadeIn('fast');
        $('#confirm-empty').fadeOut('fast');
        return itemsField.focus();
      } else {
        emptyButton.fadeIn('fast');
        itemsField.val(defaultTaskList);
        return itemsField.focus();
      }
    });
    $('#do-not-recall').click(function() {
      $('#confirm-recall-of-defaults').fadeOut('fast');
      return itemsField.focus();
    });
    $('#do-recall').click(function() {
      $('#confirm-recall-of-defaults').fadeOut('fast');
      emptyButton.fadeIn('fast');
      itemsField.val(defaultTaskList);
      return itemsField.focus();
    });
    emptyButton = $('#empty-button');
    emptyButton.click(function() {
      $('#confirm-empty').fadeIn('fast');
      $('#confirm-recall-of-defaults').fadeOut('fast');
      return itemsField.focus();
    });
    $('#do-not-empty').click(function() {
      $('#confirm-empty').fadeOut('fast');
      return itemsField.focus();
    });
    $('#do-empty').click(function() {
      $('#confirm-empty').fadeOut('fast');
      itemsField.val('');
      emptyButton.fadeOut('fast');
      return itemsField.focus();
    });
    ZeroClipboard.config({
      moviePath: 'js/vendor/ZeroClipboard.swf'
    });
    client = new ZeroClipboard($('#copy-button'));
    client.on('load', function(client) {
      return client.on('datarequested', function(client) {
        return client.setText($('#taskpaper-month').val());
      });
    });
    client.on('noFlash', function() {
      $('#copy-button').hide();
      return console.error('No Flash installed. Hiding the \'Copy\' button.');
    });
    return client.on('wrongFlash', function() {
      $('#copy-button').hide();
      return console.error('Wrong Flash installed. Hiding the \'Copy\' button.');
    });
  });

}).call(this);
